[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
ignore = ['E231', 'E241']
per-file-ignores = [
    '__init__.py:F401',
]
exclude = [
    'config',
    'migrations',
    '.git',
    '.gitignore',
    '__pycache__',
]
max-line-length = 120
count = true
